version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis:6379
      - COIN_GECKO_API_KEY=${COIN_GECKO_API_KEY}
      - ZORA_SWAP_CONTRACT=${ZORA_SWAP_CONTRACT}
      - GELATO_API_KEY=${GELATO_API_KEY}
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  redis_data: